# docker compose up -d
# docker exec -it alf_container bash

# THEN!!! The only thing needed to do afterwards is to put the vcj models into
# the /opt/alf/infiles directory

services:
  alf:
    build:
      context: .
      dockerfile: Dockerfile
    image: tansb/alf
    container_name: alf_container
    volumes:
        - ${MY_MOUNTED_DATA_DIR}:/mnt
    stdin_open: true
    tty: true
    entrypoint: []
    command: ["/bin/bash"]
